"""Central config: paths, column names, hyperparam defaults.

The dataset lives outside the worktree at ``/Users/alberto/Desktop/code/JaneStreetChallenge/data``
in the canonical Kaggle layout (partitioned parquet directories).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

# ---------------------------------------------------------------------------
# Column names — match the Kaggle dataset exactly.
# ---------------------------------------------------------------------------
COL_DATE = "date_id"
COL_TIME = "time_id"
COL_ID = "symbol_id"
COL_WEIGHT = "weight"
COL_TARGET = "responder_6"

# 9 native responders (responder_0..responder_8). Two synthetic aux responders
# (responder_9, responder_10) are generated by feature engineering.
COLS_RESPONDERS_NATIVE = [f"responder_{i}" for i in range(9)]

# 79 native features.
COLS_FEATURES_INIT = [f"feature_{i:02d}" for i in range(79)]

# Categoricals — Volkova drops these.
COLS_FEATURES_CAT = ["feature_09", "feature_10", "feature_11"]

# The 16 high-correlation features that get rolling stats + market-avg added,
# verbatim from data_processor.py in the 8th-place repo.
COLS_FEATURES_CORR = [
    "feature_06", "feature_04", "feature_07", "feature_36",
    "feature_60", "feature_45", "feature_56", "feature_05",
    "feature_51", "feature_19", "feature_66", "feature_59",
    "feature_54", "feature_70", "feature_71", "feature_72",
]


@dataclass
class Cfg:
    """All configuration in one place. Override fields per run.

    The default ``data_root`` points at the absolute path the user wired into
    the project. Override via the CLI ``--data-root`` flag for portability.
    """

    # --- paths ---
    data_root: Path = Path(
        "/Users/alberto/Desktop/code/JaneStreetChallenge/data"
    )
    artifacts_root: Path = Path(
        "/Users/alberto/Desktop/code/JaneStreetChallenge/.claude/worktrees"
        "/infallible-robinson-eb8ba6/artifacts"
    )

    # --- data filtering ---
    # Volkova starts from date_id=700 (when time_id counts stabilize at 968).
    min_date_id: int = 700
    # When iterating quickly use a date cap; None = no cap.
    max_date_id: int | None = None
    # Rolling window length for per-symbol stats.
    rolling_window: int = 1000
    # Time_ids per date — used to reshape (sym,date,time) chunks. Stable at 968.
    n_times_per_date: int = 968

    # --- targets ---
    target: str = COL_TARGET
    # Auxiliary heads. Volkova trains the y head plus four aux heads predicting
    # the last 4 columns of the "other responders" array (r7, r8, r9, r10 in
    # her ordering after synthesizing r9 and r10).
    aux_targets: list[str] = field(default_factory=lambda: [
        "responder_7", "responder_8", "responder_9", "responder_10",
    ])
    # Lagged (previous-day) responders to add as INPUT features. At date d,
    # ``responder_{r}_lag1d`` = responder_r from date d-1 at the same
    # (symbol, time_id) — exactly what the competition's lags.parquet
    # provides at inference, so it's deployable and strictly backward-looking
    # (no leakage). Empty = off. This is TimeXer's "endogenous" series when
    # r includes the target (responder_6).
    lagged_responders: list[int] = field(default_factory=list)
    # Engineered signals derived from the lagged responders, motivated by the
    # "Reverse Engineering the Responders" analysis (Kaggle #555562): the
    # responders are forward-shifted moving averages of two exchanges' signals
    # at windows SMA-4/20/120 — {6,7,8}=exchange A (SMA20/120/4),
    # {3,4,5}=exchange B, {0,1,2}=their difference. Cross-window differences of
    # the (lagged) responders are multi-scale momentum of the underlying;
    # cross-exchange differences are the venue spread. All are diffs of
    # already-lagged (previous-day) values → strictly backward-looking, no leak.
    # Requires lagged_responders to include {3,4,5,6,7,8}.
    responder_signal_features: bool = False

    # --- CV ---
    n_splits: int = 2
    test_size_dates: int = 200
    cv_gap_dates: int = 0  # set to 200 when imitating the "test gap" run

    # --- model ---
    model_name: str = "gru_modelr"   # see janestreet.models registry
    model_kwargs: dict = field(default_factory=dict)

    # --- training ---
    epochs: int = 25
    batch_size: int = 1              # one date per batch (Volkova)
    lr: float = 1e-3
    weight_decay: float = 1e-2
    grad_clip: float = 1.0
    early_stopping_patience: int = 10
    online_lr_refit: float = 3e-4
    seed: int = 42
    device: str = "auto"             # "auto" | "cpu" | "cuda" | "mps"

    # --- misc ---
    verbose: bool = True
    num_workers: int = 0

    # ------------------------------------------------------------------
    @property
    def train_parquet(self) -> Path:
        return self.data_root / "train.parquet"

    @property
    def test_parquet(self) -> Path:
        return self.data_root / "test.parquet"

    @property
    def lags_parquet(self) -> Path:
        return self.data_root / "lags.parquet"


def default_cfg() -> Cfg:
    return Cfg()
